#ifndef defs
#define defs
#define WIDTH_WINDOW 1200
#define HEIGHT_WINDOW 800

#define GAMEMODE_SINGLEPLAYER 0
#define GAMEMODE_MULTIPLAYER 1

#define CHARACTER_FRAMES 90

#define FIRETRAP_FRAMES_LV1 200
#define FIRETRAP_FRAMES_LV2 175
#define FIRETRAP_FRAMES_LV3 250

#define CEILINGTRAP_FRAMES_LV1_LOW 250
#define CEILINGTRAP_FRAMES_LV1_MEDIUM 150
#define CEILINGTRAP_FRAMES_LV1_FAST 75

#define SAWTRAP_FRAMES_LV1 150

#define WIDTH_PLAYER_IDLE 19
#define HEIGHT_PLAYER_IDLE 32

#define WIDTH_PLAYER_RUN 21
#define HEIGHT_PLAYER_RUN 33

#define WIDTH_PLAYER_JUMP 20
#define HEIGHT_PLAYER_JUMP 35

#define WIDTH_PLATFORM_1 235
#define HEIGHT_PLATFORM_1 55

#define WIDTH_PLATFORM_3 336
#define HEIGHT_PLATFORM_3 159

#define WIDTH_PLATFORM_5 402
#define HEIGHT_PLATFORM_5 62

#define WIDTH_PLATFORM_6 50
#define HEIGHT_PLATFORM_6 50

#define NUM_OF_LEDGES 50
#define GRAVITY 0.25f

#define STATUS_STATE_LIVES 0
#define STATUS_STATE_GAME 1
#define STATUS_STATE_GAMEOVER 2

#define MAP_WIDTH 24
#define MAP_HEIGHT 16

#define PLX_BACKGROUND_1 1
#define PLX_BACKGROUND_2 6
#define PLX_BACKGROUND_3 5
#define PLX_BACKGROUND_4 4
#define PLX_BACKGROUND_5 3
#endif // !defs