#ifndef defs
#define defs
#define WIDTH_WINDOW 1200
#define HEIGHT_WINDOW 800

#define STATUS_STATE_GAME 0
#define STATUS_STATE_GAMEOVER 1 // gameover = bad end
#define STATUS_STATE_TRUE_END 2
#define STATUS_STATE_GOOD_END 3

#define END_OF_GAME_POSITION 1 // position where if player.x >= END_OF_GAME_POSITION -> gameState.statusState = TRUE END || GOOD END
#define GAMEMODE_SINGLEPLAYER 0
#define GAMEMODE_MULTIPLAYER 1

#define DIFFICULTY_EASY 5
#define DIFFICULTY_MEDIUM 3
#define DIFFICULTY_HARD 1

#define MAX_HEALTH_EASY 5
#define MAX_HEALTH_MEDIUM 3
#define MAX_HEALTH_HARD 1
#define REQUIRED_HEALTH_POTION 5
#define CHARACTER_FRAMES 90

#define ITEM_TYPE_NORMAL 0
#define ITEM_TYPE_FIRST_AID_KIT 1
#define ITEM_TYPE_HEALTH_POTION 2
#define ITEM_TYPE_SMOL_GOLEM 3
#define ITEM_TYPE_KEY 4

#define FIRST_AID_KIT_FRAMES 100

#define FIRETRAP_FRAMES_LV1 200
#define FIRETRAP_FRAMES_LV2 175
#define FIRETRAP_FRAMES_LV3 250

#define CEILINGTRAP_FRAMES_LV1_LOW 250
#define CEILINGTRAP_FRAMES_LV1_MEDIUM 150
#define CEILINGTRAP_FRAMES_LV1_FAST 75

#define SAWTRAP_FRAMES_LV1 150

#define LIGHTNING_TRAP_LV2_FAST 100
#define LIGHTNING_TRAP_LV2_MEDIUM 110
#define LIGHTNING_TRAP_LV2_SLOW 130
#define LIGHTNING_TRAP_LV2_SUPER_SLOW 150

#define SMOL_GOLEM_FRAMES 100
#define SMOL_GOLEM_SPEED 40
#define SMOL_GOLEM_DETECT_RANGE 150
#define GIGA_GOLEM_FRAMES 100
#define GIGA_GOLEM_SPEED 70

#define WIDTH_GIGA_GOLEM 150
#define HEIGHT_GIGA_GOLEM 150

#define WIDTH_PLAYER_IDLE 19
#define HEIGHT_PLAYER_IDLE 32

#define WIDTH_PLAYER_RUN 21
#define HEIGHT_PLAYER_RUN 33

#define WIDTH_PLAYER_JUMP 20
#define HEIGHT_PLAYER_JUMP 35

#define WIDTH_PLATFORM_1 235
#define HEIGHT_PLATFORM_1 55

#define WIDTH_PLATFORM_3 336
#define HEIGHT_PLATFORM_3 159

#define WIDTH_PLATFORM_5 402
#define HEIGHT_PLATFORM_5 62

#define WIDTH_PLATFORM_6 50
#define HEIGHT_PLATFORM_6 50

#define NUM_OF_LEDGES 50
#define GRAVITY 0.25f

#define MAP_WIDTH 24
#define MAP_HEIGHT 16

#define PLX_BACKGROUND_1 1
#define PLX_BACKGROUND_2 6
#define PLX_BACKGROUND_3 5
#define PLX_BACKGROUND_4 4
#define PLX_BACKGROUND_5 3
#endif // !defs