#ifndef defs
#define defs
#define WIDTH_WINDOW 1200
#define HEIGHT_WINDOW 800
#define WIDTH_PLAYER_IDLE 19
#define HEIGHT_PLAYER_IDLE 32
#define WIDTH_PLAYER_RUN 21
#define HEIGHT_PLAYER_RUN 33
#define WIDTH_PLAYER_LEDGEGRAB 20
#define HEIGHT_PLAYER_LEDGEGRAB 40
#define WIDTH_PLAYER_JUMP 20
#define HEIGHT_PLAYER_JUMP 35
#define WIDTH_PLATFORM_1 235
#define HEIGHT_PLATFORM_1 55
#define WIDTH_PLATFORM_3 336
#define HEIGHT_PLATFORM_3 159
#define WIDTH_PLATFORM_5 402
#define HEIGHT_PLATFORM_5 62
#define WIDTH_PLATFORM_6 50
#define HEIGHT_PLATFORM_6 50
#define NUM_OF_LEDGES 100
#define GRAVITY 0.2f
#define STATUS_STATE_LIVES 0
#define STATUS_STATE_GAME 1
#define STATUS_STATE_GAMEOVER 2
#define MAP_WIDTH 24
#define MAP_HEIGHT 16
#endif // !defs